### ISSUE TITLE
Scale issue in windows

### ISSUE THREAD

**Issue by liver121888** [salvatoreromeo/osd-hotkey#1]
In my display setting, I use 125% scale to view the screen. 

![image](https://user-images.githubusercontent.com/68542467/152744138-d70c83b3-a3ba-4294-921b-cf65e13c3218.png)

And every time I restart the osd-hotkey, the window size expands, and the window position is changed.
Can it be an option to adjusted to fix the size in this situation?
Also, the window is not movable in my case. (You can see there is no window bar)

![image](https://user-images.githubusercontent.com/68542467/152744487-9b22f9da-5d50-46a6-8f72-1d39ecbfbbb8.png)

**Comment by salvatoreromeo** [comment]
hi liver, I made it open source since I don't have time to work on it anymore. If you want to send a PR, I will be glad to review it. Anyway, the code is written using AutoHotkey, a simple macro language. To save the position and size of the window, you can use the INI file and edit the script using the docs here: https://www.autohotkey.com/docs/commands/IniRead.htm

**Comment by liver121888** [comment]
I have tried to modify the ini file and set the x y height width, but the value would also change every time the OSD starts up. So maybe I will try to study the AutoHotkey myself and program it when I am free. Thanks for your reply.
